//USER REGISTRATION
export const USER_REGISTER_REQUEST: string = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS: string = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL: string = "USER_REGISTER_FAIL";

//USER LOGIN
export const USER_LOGIN_REQUEST: string = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS: string = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL: string = "USER_LOGIN_FAIL";
export const USER_LOGOUT: string = "USER_LOGOUT";

//USER PROFILE
export const USER_PROFILE_REQUEST: string = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS: string = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL: string = "USER_PROFILE_FAIL";

//USER UPDATE
export const USER_UPDATE_REQUEST: string = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS: string = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL: string = "USER_UPDATE_FAIL";

// FETCH USERS
export const USER_FETCH_REQUEST: string = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS: string = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL: string = "CREATE_USERS_FAIL";

//TODOS

export const TODO_CREATE_REQUEST: string = "TODO_CREATE_REQUEST";
export const TODO_CREATE_SUCCESS: string = "TODO_CREATE_SUCCESS";
export const TODO_CREATE_FAIL: string = "TODO_CREATE_FAIL";

// FETCH TODOS
export const TODO_FETCH_REQUEST: string = "TODO_FETCH_REQUEST";
export const TODO_FETCH_SUCCESS: string = "TODO_FETCH_SUCCESS";
export const TODO_FETCH_FAIL: string = "TODO_FETCH_FAIL";

//DELETE TODOS
export const TODO_DELETE_REQUEST: string = "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS: string = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL: string = "TODO_DELETE_FAIL";

//TODO DETAILS
export const TODO_DETAIL_REQUEST: string = "TODO_DETAIL_REQUEST";
export const TODO_DETAIL_SUCCESS: string = "TODO_DETAIL_SUCCESS";
export const TODO_DETAIL_FAIL: string = "TODO_DETAIL_FAIL";

//UPDATE TODOS
export const TODO_UPDATE_REQUEST: string = "TODO_UPDATE_REQUEST";
export const TODO_UPDATE_SUCCESS: string = "TODO_UPDATE_SUCCESS";
export const TODO_UPDATE_FAIL: string = "TODO_UPDATE_FAIL";

//COMPLETE TODOS
export const TODO_COMPLETE_REQUEST: string = "TODO_COMPLETE_REQUEST";
export const TODO_COMPLETE_SUCCESS: string = "TODO_COMPLETE_SUCCESS";
export const TODO_COMPLETE_FAIL: string = "TODO_COMPLETE_FAIL";

//TODO CATEGORIES

export const TODO_CATEGORY_CREATE_REQUEST: string =
  "TODO_CATEGORY_CREATE_REQUEST";
export const TODO_CATEGORY_CREATE_SUCCESS: string =
  "TODO_CATEGORY_CREATE_SUCCESS";
export const TODO_CATEGORY_CREATE_FAIL: string = "TODO_CATEGORY_CREATE_FAIL";

// FETCH TODO CATEGORIES
export const TODO_CATEGORY_FETCH_REQUEST: string =
  "TODO_CATEGORY_FETCH_REQUEST";
export const TODO_CATEGORY_FETCH_SUCCESS: string =
  "TODO_CATEGORY_FETCH_SUCCESS";
export const TODO_CATEGORY_FETCH_FAIL: string = "TODO_CATEGORY_FETCH_FAIL";

//DELETE TODO CATEGORIES
export const TODO_CATEGORY_DELETE_REQUEST: string =
  "TODO_CATEGORY_DELETE_REQUEST";
export const TODO_CATEGORY_DELETE_SUCCESS: string =
  "TODO_CATEGORY_DELETE_SUCCESS";
export const TODO_CATEGORY_DELETE_FAIL: string = "TODO_CATEGORY_DELETE_FAIL";

//TODO DETAILS
export const TODO_CATEGORY_DETAIL_REQUEST: string =
  "TODO_CATEGORY_DETAIL_REQUEST";
export const TODO_CATEGORY_DETAIL_SUCCESS: string =
  "TODO_CATEGORY_DETAIL_SUCCESS";
export const TODO_CATEGORY_DETAIL_FAIL: string = "TODO_CATEGORY_DETAIL_FAIL";

//UPDATE TODO CATEGORIES
export const TODO_CATEGORY_UPDATE_REQUEST: string =
  "TODO_CATEGORY_UPDATE_REQUEST";
export const TODO_CATEGORY_UPDATE_SUCCESS: string =
  "TODO_CATEGORY_UPDATE_SUCCESS";
export const TODO_CATEGORY_UPDATE_FAIL: string = "TODO_CATEGORY_UPDATE_FAIL";

//COMPLETE TODO CATEGORIES
export const TODO_CATEGORY_COMPLETE_REQUEST: string =
  "TODO_CATEGORY_COMPLETE_REQUEST";
export const TODO_CATEGORY_COMPLETE_SUCCESS: string =
  "TODO_CATEGORY_COMPLETE_SUCCESS";
export const TODO_CATEGORY_COMPLETE_FAIL: string =
  "TODO_CATEGORY_COMPLETE_FAIL";
