//USER REGISTRATION
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//USER LOGIN
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

//USER PROFILE
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

//USER UPDATE
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

// FETCH USERS
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "CREATE_USERS_FAIL";

//TODOS

export const TODO_CREATE_REQUEST = "TODO_CREATE_REQUEST";
export const TODO_CREATE_SUCCESS = "TODO_CREATE_SUCCESS";
export const TODO_CREATE_FAIL = "TODO_CREATE_FAIL";

// FETCH TODOS
export const TODO_FETCH_REQUEST = "TODO_FETCH_REQUEST";
export const TODO_FETCH_SUCCESS = "TODO_FETCH_SUCCESS";
export const TODO_FETCH_FAIL = "TODO_FETCH_FAIL";

//DELETE TODOS
export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL";

//TODO DETAILS
export const TODO_DETAIL_REQUEST = "TODO_DETAIL_REQUEST";
export const TODO_DETAIL_SUCCESS = "TODO_DETAIL_SUCCESS";
export const TODO_DETAIL_FAIL = "TODO_DETAIL_FAIL";

//UPDATE TODOS
export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST";
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS";
export const TODO_UPDATE_FAIL = "TODO_UPDATE_FAIL";

//COMPLETE TODOS
export const TODO_COMPLETE_REQUEST = "TODO_COMPLETE_REQUEST";
export const TODO_COMPLETE_SUCCESS = "TODO_COMPLETE_SUCCESS";
export const TODO_COMPLETE_FAIL = "TODO_COMPLETE_FAIL";
